version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    labels:
      - 'js'
      - 'dependencies'
    ignore:
      - dependency-name: '@cloudflare/workers-types'
    groups:
      aws:
        patterns:
          - '@aws-sdk/*'
      oxc:
        patterns:
          - 'ox*'
      types:
        patterns:
          - '@types/*'
      cloudflare:
        patterns:
          - 'wrangler'
          - '@cloudflare/*'
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    groups:
      actions:
        patterns:
          - 'actions/*'
    labels:
      - 'dependencies'
      - 'github-actions'
