packages:
  - web
  - registry
  - packages/*

catalog:
  '@cloudflare/workers-types': 4.20260123.0
  '@types/bun': 1.3.14
  '@types/node': 25.9.0
  '@types/semver': 7.7.1
  'hono': 4.12.18
  'postgres': 3.4.9
  'semver': 7.8.0
  'typescript': 6.0.3
  'wrangler': 4.90.1
  'zod': 4.4.3
  'vite': npm:@voidzero-dev/vite-plus-core@0.1.21
  'vitest': npm:@voidzero-dev/vite-plus-test@0.1.21
  'vite-plus': 0.1.21

packageConfigs:
  - match: ['*']
    saveExact: true

catalogMode: strict
minimumReleaseAge: 1440
minimumReleaseAgeStrict: strict
allowBuilds:
  '@clerk/shared': false
  'browser-tabs-lock': false
  'bufferutil': false
  'core-js': false
  'esbuild': false
  'sharp': false
  'utf-8-validate': false
  'workerd': false
