---
name: cache

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-cache-buster
  cancel-in-progress: true

jobs:
  bust:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: delete action cache
        run: gh cache delete --all --succeed-on-no-caches --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
