name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1.6.0
        with:
          cache: true
          node-version: 24

      - name: install dependencies
        run: vp install --frozen-lockfile --ignore-scripts

      - name: generate types
        run: vp run typegen

      - name: check
        run: vp check

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1.6.0
        with:
          cache: true

      - name: install dependencies
        run: vp install --frozen-lockfile --ignore-scripts

      - name: run tests
        run: vp test
